name: BUG 提交 / BUG Report
description: 反馈 bug / Report bugs to developers
title: "[BUG] "
labels: ["BUG"]
body:
  - type: checkboxes
    attributes:
      label: 确认 / Assignments
      description: 提交issue请确保完成以下前提，否则该issue可能被忽略 / Make sure you read checkboxs below
      options:
        - label: 阅读[Sigma 版本 最新稳定版](https://github.com/Luoyacheng/legado-E/releases/latest)依然存在此问题 / Latest beta app does not work
          required: true
        - label: 书源[最新版本](https://github.com/DowneyRem/PixivSource/releases/latest)依然存在此问题 / Latest source does not work
          required: true
        - label: 使用书源🐞调试，确认并非站方限制 / 🐞DEBUG SOURCE, Confirm it is not restricted by the site
          required: true
        - label: 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc
          required: true

  - type: textarea
    attributes:
      label: 问题描述 & 复现步骤 / Describe Bugs & How to reproduce
    validations:
      required: true
  - type: textarea
    attributes:
      label: 出现问题的小说链接 / BUG Novels URL Link
      placeholder: |
        https://www.pixiv.net/novel/show.php?id=123
        https://www.pixiv.net/novel/series/123

  - type: textarea
    attributes:
      label: 调试信息（我的-编辑书源-🐞调试源，输入书名或链接） / 🐞Debug Message in Legado 
      description: |
        目录：```++https://www.pixiv.net/novel/show.php?id=123```
        正文：```--https://www.pixiv.net/novel/show.php?id=123```
      placeholder: |
        下述情况大概率是 Pixiv 限制，并非书源错误。请 过段时间/重新登陆 后再尝试
        {"error":true, "message":"出现错误。请稍后再试。", "body":[]}
  
  - type: checkboxes
    attributes:
      label: 确认 / Assignment
      options:
        - label: 已经提交复现所需要的附加资料 / Submit additions related with bugs
          required: true

  - type: input
    attributes:
      label: 软件分支 / Legado Fork version
      description: |
        不同的阅读分支：Sigma, MD3 等分支版本或仓库链接
      placeholder: "Sigma"
    validations:
      required: true
      
  - type: input
    attributes:
      label: 阅读版本 / Legado version
      description: |
        阅读 - 我的 - 关于- 更新日志
      placeholder: "3.22.110823"
    validations:
      required: true
        
  - type: input
    attributes:
      label: 书源版本 / Source Version
      description: |
        书源版本1：发现 - 更新 - 阅读本地版本
        书源版本2：我的 - 编辑 - 源注释
        书源版本3：我的 - 书源管理 - Pixiv书源 - 调试 - 测试页面
      placeholder: "200 或 2025/06/01"
    validations:
      required: true
      
